#!/usr/bin/env bash

set -e
set -x

isort --force-single-line-imports app app/tests
autoflake --recursive --remove-all-unused-imports --remove-unused-variables --in-place app app/tests
isort app app/tests
